name: "Newman Tests"
on: [push, pull_request]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      # Checks-out your repository
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run Tests
        uses: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json
     
